<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=15">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Secretaría de Estado de Comunicación<br>MASCI, Diego</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaria Privada<br>ORTEGA, Claudia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Asesoría Contable y Presupuestaria<br>ANZULOVICH, Cecilia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Dirección General de San Luis +<br>PASCUARELLI, Emiliano</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.3.1.</span></div><div class="col">Subdirección Periodística y Artística<br>SIN DESIGNACIÓN</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.3.1.1.</span></div><div class="col">Área de Coordinación de Producción Periodística<br>GONZALVES, Carolina Verónica</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.3.2.</span></div><div class="col">Subdirección Administrativa y Contable<br>SOLANES, Lisandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.3.2.1.</span></div><div class="col">Área de Publicidad<br>GRACIANO, José Emilio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.3.3</span></div><div class="col">Subdirección de Recursos Humanos<br>PASCUARELLI, Federico</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.3.4.</span></div><div class="col">Subdirección Técnica<br>FLORES, Carlos</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Dirección de San Luis + Streaming<br>GURLINO, Adriana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.4.1.</span></div><div class="col">Subdirección de Desarrollo en Redes<br>SUAREZ GARCIA, Luciana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Dirección General de Agencia de Noticias San Luis<br>DIAZ, Gustavo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.1.</span></div><div class="col">Subdirección de Redacción<br>DETTONI, Marcelo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.2.</span></div><div class="col">Subdirección de Contenidos en Medios Tradicionales<br>BARBATO, Germán</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.3.</span></div><div class="col">Subdirección de Desarrollo en Redes<br>VILALLONGA, Juan Martin</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.4.</span></div><div class="col">Subdirección Administrativo y de Registro de Medios<br>ITURRIOZ, Juan Pablo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Dirección de Producción Multimedia<br>NIETO, Sergio Ricardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.1.</span></div><div class="col">Subdirección de Fotografía<br>USET, Fabian</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Dirección de Desarrollo Estratégico y Vinculación Gubernamental<br><small>ARRIETA, Esteban</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.1.</span></div><div class="col">Subdirección de Vinculación Ciudadana<br><small>SINDONI PROTO, Gabriel</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.2.</span></div><div class="col">Subdirección Web Oficial Poder Ejecutivo<br>FERRERO, Gianfranco</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.8.</span></div><div class="col">Dirección de Atención Ciudadana en Redes Sociales Oficiales<br>ESCUDERO, Exequiel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.1.</span></div><div class="col">Área de Atención Virtual Ciudadana<br>AMAYA, Karem</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.9.</span></div><div class="col">Dirección de Coordinación y Planificación<br>RODRIGUEZ, Antonella</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.10.</span></div><div class="col">Dirección de Contenidos Audiovisuales<br>KREMNITZER, Valeria</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.11.</span></div><div class="col">Dirección de Desarrollo de Contenidos en Redes Sociales Oficiales<br>COLAFRANCESCO, Pablo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.1.</span></div><div class="col">Área de Contenido en Redes Sociales Oficiales<br>SIN DESIGNACIÓN</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 30/10/2024 09:50</p>