<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=16">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Secretaría de Estado de Deporte<br>MUÑIZ, Maria Adelaida</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaria Privada<br>CLEMENTE MUÑIZ OLIVERA AGUIRRE, Ricardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Despacho<br>GARRIDO, Vanesa Del Carmen</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Asesoría Legal<br>CHADA FENOY, Laura Cecilia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Asesoria Contable y Presupuestaria<br>LÓPEZ ALCARÁZ , Fabiana Solange</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Subdirección de Comunicación Institucional<br>ACOSTA, Andrés</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Dirección de Deporte Comunitario<br>NADAL, Pedro Luis</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.1.</span></div><div class="col">Subdirección de Vinculación Municipal<br>QUIROGA PAEZ, Alan Federico</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.1.1.</span></div><div class="col">Área Eventos Provinciales<br>UBILLOS, Martin Andres</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.2.</span></div><div class="col">Subdirección de Planes Deportivos Provinciales<br>LUBERRIAGA, Mariana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.1.</span></div><div class="col">Área Coordinación Operativa Natatorios Merlo y Concarán<br>CORONEL, Alejandro Sebastian</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.2.</span></div><div class="col">Área Coordinación Operativa Natatorio El Volcán<br>PERALTA, Manuel Patricio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.3.</span></div><div class="col">Área Coordinación Operativa Pista de Atletismo Pedro Presti<br>BARDUCCO, Andrea Mariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.3.</span></div><div class="col">Subdirección de Deporte para Todos<br>QUIROGA, Diego Adrian</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Dirección de Deporte Estudiantil<br>FERNANDEZ TODISCO, Maria Andrea</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.1.</span></div><div class="col">Subdirección de Juegos Deportivos Intercolegiales<br>FUENTES, Diego Ramiro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.1.</span></div><div class="col">Área Coordinación Regional<br>MOYANO BECERRA, Miguel Angel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.2.</span></div><div class="col">Área Transporte<br>FUNES, Estela Mary</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.3.</span></div><div class="col">Área Competencia<br>BARBEITO LAFOURCADE, Juan Hilario</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.4.</span></div><div class="col">Área Coordinación y Logística<br>ARANCIVA BENITEZ, Carolina Inés</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.8.</span></div><div class="col">Dirección de Desarrollo Deportivo<br>CAPALDO, Laura Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.1.</span></div><div class="col">Área Administración<br>LATTES, Mariana Belen</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.2.</span></div><div class="col">Área Coordinación Operativa Estadio Provincial Juan Gilberto Funes<br>PERANO, German Alfredo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.3.</span></div><div class="col">Área Desarrollo de Deportes Urbanos y Coordinación Operativa Trinquete Modelo y Velódromo<br>MARTINEZ, Andres David</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.4.</span></div><div class="col">Subdirección del Centro de Desarrollo Villa Deportiva<br>JOLOIDOVSKY, Javier Enrique</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.4.1.</span></div><div class="col">Área Coordinación Deportiva<br>LUBERRIAGA, Mariana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.5.</span></div><div class="col">Subdirección del Centro de Desarrollo Deportivo Ave Fénix<br>ACEVEDO, Bruno</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.5.1.</span></div><div class="col">Área Coordinación Deportiva<br>TONTI SILVA, Carlos Ariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.6.</span></div><div class="col">Subdirección de Infraestructura<br>RODRIGUEZ, Fabian Esteban</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.6.1.</span></div><div class="col">Área Planeamiento y Arquitectura<br>PETRINO, Maria Guadalupe</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.6.2.</span></div><div class="col">Área Intendencia<br>MANCUELLO, Florentina Ramona</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.9.</span></div><div class="col">Dirección de Deporte Federado<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.1.</span></div><div class="col">Subdirección de Fortalecimiento Institucional de Clubes<br>ECHENIQUE PAGANO, Carla Valentina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.1.1.</span></div><div class="col">Área Capacitaciones<br>AIMAR, Damian Eduardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.2.</span></div><div class="col">Subdirección de Desarrollo Federativo<br>BENAVIDEZ, Guillermo Martin</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.2.1.</span></div><div class="col">Área Selecciones Provinciales<br>MORALES, Maria Leyla Lujan</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.10.</span></div><div class="col">Dirección del Campus de Alto Rendimiento<br>VILLEGAS, Jorge Eduardo Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.1.</span></div><div class="col">Subdirección de Evaluación Deportiva<br>FERNANDEZ, Jose Emiliano</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.2.</span></div><div class="col">Subdirección de Detección de Talentos<br>GIMENEZ, Facundo Alfredo</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 14/11/2024 13:18</p>