<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=6">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Ministerio de Desarrollo Productivo<br>TROMBOTTO, Federico Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaría Privada<br>TAGUA, Cesar Dario</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Asesoria Legal<br>CAMPOS, Ignacio Abelardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Asesoria Contable y Presupuestaria<br>OLMOS NICOTRA, Andrea Cecilia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Despacho<br>VAN HAUTTE, Zulma Lorena</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Comunicación Institucional<br>RICCI SUAREZ, Augusto Jose</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Dirección de Desarrollo de Proveedores (DE.PRO.)<br>MALLEA, Fernando Ariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.1.</span></div><div class="col">Subdirección de Articulación y Redes de Proveedores<br>DE MARCO, Stella Maris</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.2.</span></div><div class="col">Subdirección de Desarrollo de Capacidades y Asistencia Técnica<br>GIL VERGÉS, María Antonieta</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.3.</span></div><div class="col">Subdirección de Gestión de Proyectos y Administración<br>GUZMAN, Diego Gabriel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.4.</span></div><div class="col">Subdirección DE.PRO. Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.5.</span></div><div class="col">Subdirección DE.PRO. Villa de Merlo<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Dirección de Fortalecimiento de La Competitividad<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.1.</span></div><div class="col">Área de Investigación y Desarrollo de Nuevos Productos y Mercados<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.2.</span></div><div class="col">Área de Competitividad Provincial<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.8.</span></div><div class="col">Dirección de Mesas Sectoriales y Mesas Regionales<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.1.</span></div><div class="col">Área Región Centro San Luis<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.2.</span></div><div class="col">Área Región Centro Este Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.3.</span></div><div class="col">Área Región Oeste<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.4.</span></div><div class="col">Área Región Llanura Sur<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.5.</span></div><div class="col">Área Región Valle Del Conlara<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.6.</span></div><div class="col">Área Región Llanura Norte<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.7.</span></div><div class="col">Área Región Norte Serrano<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.9.</span></div><div class="col">Dirección de Valor Agregado y Vinculación Compre Local<br>OLIVA, Cesar Fernando</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.1.</span></div><div class="col">Área Valor Agregado<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.2.</span></div><div class="col">Área Compre San Luis<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.3.</span></div><div class="col">Área Marca San Luis<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.10.</span></div><div class="col">Dirección de Desarrollo Productivo y Escuela<br>PAEZ, Daniela Jorgelina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.1.</span></div><div class="col">Subdirección de Desarrollo Productivo y Escuela Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.11.</span></div><div class="col">Dirección de Fiscalización y Control<br>BOIERO, Victor Daniel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.1.</span></div><div class="col">Subdirección de Control Sanitario Fiscal<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.1.1.</span></div><div class="col">Área Control Sanitario Limitrofe<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.1.2.</span></div><div class="col">Área Control Ferias y Remates<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.1.3.</span></div><div class="col">Área Control General<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.1.4.</span></div><div class="col">Área Prevencion Sanitaria Animal y Vegetal<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.2.</span></div><div class="col">Subdirección de Fiscalización Industrial y Comercial<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.2.1.</span></div><div class="col">Área Fiscalización Industria<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.2.2.</span></div><div class="col">Área Fiscalización Comercios y Servicios<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.12.</span></div><div class="col">Dirección de Producción Familiar<br>PIERDOMINICI, Diego Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.12.1.</span></div><div class="col">Subdirección de Producción, Oficios y Artesanos<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.1.1.</span></div><div class="col">Área Producción<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.1.2.</span></div><div class="col">Área Oficios y Artesanos<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.1.3.</span></div><div class="col">Área Microemprendimientos<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.12.2.</span></div><div class="col">Subdirección de Asociativismo y Cooperación<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.2.1.</span></div><div class="col">Área Asociativismo<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.2.2.</span></div><div class="col">Área Promocion de La Cooperacion<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.13.</span></div><div class="col">Dirección de Desarrollo Agropecuario<br>DEL BOSCO, Gustavo Hector</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.1.</span></div><div class="col">Subdirección de Producción Agrícola<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.1.1.</span></div><div class="col">Área Agricultura Extensiva<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.1.2.</span></div><div class="col">Área Agricultura Intensiva<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.1.3.</span></div><div class="col">Área Producción Horticola<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.2.</span></div><div class="col">Subdirección de Producción Animal<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.2.1.</span></div><div class="col">Área Ganado Mayor<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.2.2.</span></div><div class="col">Área Ganado Menor, de Granja y Avícola<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.2.3.</span></div><div class="col">Área Apicultura<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 113.2.4.</span></div><div class="col">Área Lechería<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.3.</span></div><div class="col">Subdirección de Producción de Frutos y Forestal<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.3.1.</span></div><div class="col">Área Producción de Frutos<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.3.2.</span></div><div class="col">Área Producción Forestal<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.14.</span></div><div class="col">Dirección Provincial de Minería<br>FERNANDEZ, Juan Angel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.1.</span></div><div class="col">Área Mesa de Entradas<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.2.</span></div><div class="col">Área de Despacho<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.3.</span></div><div class="col">Área Contable<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.4.</span></div><div class="col">Escribanía de Minas<br>CLOSA, Agustin Ricardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.5.</span></div><div class="col">Subdirección de Procedimiento Minero<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.5.1.</span></div><div class="col">Área de Notificaciones<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.5.2.</span></div><div class="col">Área de Archivos<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.5.3.</span></div><div class="col">Área de Catastro y Registro Productor Minero<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.14.5.3.1.</span></div><div class="col">Subárea Catastro Minero<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.14.5.3.2.</span></div><div class="col">Subárea Registro Productor Minero<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.5.4.</span></div><div class="col">Area de Ordenamiento y Control de Yacimientos de Arena<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.5.5.</span></div><div class="col">Área de Control Técnico de Mensuras<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.5.6.</span></div><div class="col">Area de Ingeniería, Geología y Sustentabilidad<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.5.7.</span></div><div class="col">Área Policía Minera<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.6.</span></div><div class="col">Subdirección Desarrollo del Plan Minero<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.6.1.</span></div><div class="col">Área Promoción de Inversiones y Valor Agregado Minero<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.6.2.</span></div><div class="col">Área Artesanos En Piedra<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.15.</span></div><div class="col">Dirección de Industria Frigorífica<br>BORIOSI, Juan Carlos Roberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.15.1.</span></div><div class="col">Área Técnica Industria Frigorífica<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.15.2.</span></div><div class="col">Área Promoción de la Industria Frigorifica<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.16.</span></div><div class="col">Dirección de Desarrollo Industrial y Energias Sustentables<br>RIOS, Juan Antonio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.16.1.</span></div><div class="col">Subdirección de Desarrollo Industrial<br>FANJUL, Juan Alvaro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.1.1.</span></div><div class="col">Área Parques y Zonas Industriales<br>PERALTA, Victor Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.1.2.</span></div><div class="col">Área Competitividad Industrial<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.16.2.</span></div><div class="col">Subdirección de Desarrollo de Energías Sustentables<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.2.1.</span></div><div class="col">Área Bio Energias<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.2.2.</span></div><div class="col">Área Promocion y Eficiencia Energetica<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.17.</span></div><div class="col">Dirección de Comercio y Servicios<br>MOHR, Horacio Sebastian</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.17.1.</span></div><div class="col">Área de Comercio y Servicios Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.17.2.</span></div><div class="col">Área de Comercio y Servicios Merlo<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.18.</span></div><div class="col">Ente de Desarrollo Aeronáutico (EDA)<br>QUIROGA, Horacio Antonio</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 11/09/2024 13:18</p>