<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=7">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Ministerio de Desarrollo Humano<br>BERTOLINI, Gustavo Antonio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaría Privada<br>ALANIZ, Franco Ramon</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Despacho<br>BUSTOS, Cecilia Del Valle</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Asesor Legal<br>MUÑIZ OLIVERA AGUIRRE, Hector Fernando</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Asesoría Contable y Presupuestaria<br>GARRO BLANCO, Maria Eugenia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Subdirección Comunicación<br>ARRIETA, Mariela</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Dirección de Primera Infancia, Niñez, Adolescencia y Familia<br>PETRINO, Maria Liliana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.1.</span></div><div class="col">Subdirección de Centros de Desarrollo Infantil - Gestión - Planificación - Pedagogía - Estadística<br>ALBISU, Silvia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.1.1.</span></div><div class="col">Área Recursos Humanos<br>FERNANDEZ, Esther Ines</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.1.2.</span></div><div class="col">Área Pedagógica y Formación<br>CONTRERAS LOZA, Maria Alejandra </div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.1.3.</span></div><div class="col">Área Seguridad<br>VASQUEZ, Monica Viviana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.2.</span></div><div class="col">Subdirección de Centros de Desarrollo Infantil- Gestión Territorial<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.1.</span></div><div class="col">Área Supervisión Zona I<br>PALLERO, Nadia Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.2.</span></div><div class="col">Área Supervisión Zona II<br>ORELLANA SCACCIA, Carina Del Rosario</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.3.</span></div><div class="col">Área Supervisión Zona III<br>GARCIA, Angie Catherin</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.4.</span></div><div class="col">Área Supervisión Zona IV<br>MAZZIERI, Maria Alejandra</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.5.</span></div><div class="col">Área Supervisión Zona V<br>GARIBOTTO, Maria Susana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.6.</span></div><div class="col">Área Supervisión Zona VI<br>GARAY, Monica Lucia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.3.</span></div><div class="col">Subdirección Protección Niñez, Adolescencia y Familia<br>CORICA, Leonardo Javier</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.3.1.</span></div><div class="col">Área Familia Solidaria.<br>MORCON, Maria Solana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.3.2.</span></div><div class="col">Área Promoción, Protección de Derechos y Fortalecimiento Familiar<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.3.3.</span></div><div class="col">Área Villa Mercedes<br>BUSTOS, Marcela Alejandra</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.3.4.</span></div><div class="col">Área Villa de Merlo<br>URQUIZA, Adrian Nicolas</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.4.</span></div><div class="col">Subdirección Infraestructura y Logística<br>BECERRA, Cristina Elizabet</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Dirección de Inclusión Laboral<br>SPILLMAN, Daniel Eduardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.1.</span></div><div class="col">Subdirección Promoción Del Trabajo<br>GREGORIO MITSE, Carlos Ezequiel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.1.</span></div><div class="col">Área Desarrollo y Capital Humano<br>PASTRAN, Néstor Alfredo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.2.</span></div><div class="col">Área Administración<br>ZALAZAR, Felisa Magdalena</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.3.</span></div><div class="col">Área Asistencia y Vinculación<br>MALDONADO, Fabiola Daniela</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.8.</span></div><div class="col">Dirección Infraestructura Social<br>QUINTILLA, Jose</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.1.</span></div><div class="col">Subdirección Técnica<br>SUANO, Facundo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.1.1.</span></div><div class="col">Área Infraestructura Social Z | A<br>SOSA, Jaime David</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.1.2.</span></div><div class="col">Área Infraestructura Social Z | B<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.1.3.</span></div><div class="col">Área Infraestructura Social Z || A<br>FALCON, Fulvio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.1.4.</span></div><div class="col">Área Infraestructura Social Z || B<br>RODRIGUEZ, Eduardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.9.</span></div><div class="col">Dirección Emergencia Social<br>GARCIA, Maria Celeste </div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.1.</span></div><div class="col">Subdirección - Abordaje Comunitario<br>PREVE, Cesar Esteban</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.1.1.</span></div><div class="col">Área Social Desconcentrada San Luis<br>DE AMO GUTIÉRREZ ,  Maria Victoria </div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.1.2.</span></div><div class="col">Área Social Desconcentrada Villa Mercedes<br>MONTENEGRO BURGOS, Rosario Tomasa</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.1.3.</span></div><div class="col">Área Seguridad Alimentaria<br>FERREYRA, Hilda Noelia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.1.4.</span></div><div class="col">Área Estrategia de Acompañamiento y Desarrollo<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.10.</span></div><div class="col">Dirección Integral de La Mujer, Género y Diversidad<br>MALTESE, María Del Carmen </div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.1.</span></div><div class="col">Subdirección Atención Integral a la Víctima de Violencia<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.10.1.1.</span></div><div class="col">Área Atención Integral Villa Mercedes<br>ROCHA AGUILERA, Roxana Elizabeth</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.10.1.2.</span></div><div class="col">Área Seguimiento Proyección y Evaluación de Casos<br>LOPEZ, Claudia Alejandra</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.10.1.3.</span></div><div class="col">Área Capacitación y Prevención<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.2.</span></div><div class="col">Subdirección Fortalecimiento de Las Políticas de Igualdad de Género<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.10.2.1.</span></div><div class="col">Área Acompañamiento y Desarrollo<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.10.2.2.</span></div><div class="col">Área Atención e Integración Social<br>AMAYA, Andrea Judith</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.11.</span></div><div class="col">Dirección Cooperativa y Mutuales<br>ARRIOLA, Cynthia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.1.</span></div><div class="col">Subdirección Abordaje Territorial<br>CARBONARI, Juan Ignacio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.1.1.</span></div><div class="col">Área Abordaje Territorial Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.2.</span></div><div class="col">Subdirección Evaluación y Seguimiento de Proyectos<br>DI GENNARO, Ricardo Martin</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.3.</span></div><div class="col">Subdirección Fiscalización y Asuntos Legales<br>APREA, Maria Antonella</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.12.</span></div><div class="col">Dirección Personas Mayores<br>SOSA, Dora Elisa </div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.12.1.</span></div><div class="col">Subdirección Fortalecimiento y Promoción de Los Derechos de Personas Mayores<br>CORREA SOSA, Mercedes Sonia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.1.1.</span></div><div class="col">Área Relaciones con la Comunidad Pueyrredón<br>CORREA, Paola Alejandra</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.1.2.</span></div><div class="col">Área Recreación Cultural<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.1.3.</span></div><div class="col">Área Recreación Deportiva<br>SOSA, Maira Eliana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.1.4.</span></div><div class="col">Área Participación Social<br>PONCE, Maria Alejandra</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.1.5.</span></div><div class="col">Área Planificación<br>DUNEL, Paula Ivana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.13.</span></div><div class="col">Dirección de Viviendas y Regularización Dominial<br>ROSSI, Hugo Rodolfo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.1.</span></div><div class="col">Subdirección Soluciones Habitacionales<br>LOMBARDI, Hector Gabriel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.2.</span></div><div class="col">Subdirección Regularización Dominial<br>DIAZ, Carola Rosana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.2.1.</span></div><div class="col">Área Recupero de Cuotas<br>SUAREZ, Marcela Carolina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.13.2.2.</span></div><div class="col">Área Control y Re Adjudicación - Escrituración - Cancelación<br>BIURRUN, Maria Estefania</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.3.</span></div><div class="col">Subdirección Asuntos Legales - Viviendas Sociales<br>VASQUEZ, Francisco Gonzalo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.4.</span></div><div class="col">Subdirección Asuntos Legales - Regularización Dominial<br>LABORDA CLAVERIE, Rosario </div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.14.</span></div><div class="col">Dirección Barrios Populares<br>MANSILLA, Joaquin Emilio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.1.</span></div><div class="col">Área Despacho<br>MONSALVA, Kevin Uriel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.2.</span></div><div class="col">Sub-Dirección Gestión Administrativa<br>BRAVERMAN, Ariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.14.2.1.</span></div><div class="col">Área Atención Al Público<br>FLORES, Damian Augusto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.3.</span></div><div class="col">Sub-Dirección Logística y Coordinación Territorial<br>VIDELA GUTIERREZ, Kevin Marciel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.14.4.</span></div><div class="col">Área Enlace Territorial<br>LUCERO, Rosa Carolina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.15.</span></div><div class="col">Dirección Sistematización y Gestión de Recursos<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.15.1.</span></div><div class="col">Subdirección Planeamiento y Proyectos<br>PUERTAS, Diego Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.15.1.1.</span></div><div class="col">Área Desarrollo Informático<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.15.2.</span></div><div class="col">Subdirección Gestión de Recursos Económicos<br><small>MALDONADO, Carlos Augusto</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.16.</span></div><div class="col">Dirección de Inclusión Social<br>TORRES, Juan Pablo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.16.1</span></div><div class="col">Subdirección Gestión Territorial Zona I<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.1.1.</span></div><div class="col">Área Pueyrredón<br>ZANGLA, Daniel Omar</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»1.16.1.2.</span></div><div class="col">Área Belgrano<br>SOSA, Juan Rolando</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.1.3.</span></div><div class="col">Área Ayacucho<br>ESCUDERO, Ramiro Ezequiel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.16.2</span></div><div class="col">Subdirección Gestión Territorial Zona II<br>SIMIOLI, Maria Antonia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.2.1.</span></div><div class="col">Área Pedernera<br>VERA, Monica Ines</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.2.2.</span></div><div class="col">Área Dupuy <br>AMILCAR BARROSO, Ariel Roberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.16.3</span></div><div class="col">Subdirección Gestión Territorial Zona III<br>NOVILLO, Ana Maria</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.3.1.</span></div><div class="col">Área Pringles<br>MEDERO, Marcela Yamile</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.3.2</span></div><div class="col">Área San Martin <br>FUNES, Cesar Javier</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.16.4</span></div><div class="col">Subdirección Gestión Territorial Zona IV<br>ALCARAZ, Franco Sebastian</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.4.1.</span></div><div class="col">Área Chacabuco<br>ORTIZ, Rodrigo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.16.4.2.</span></div><div class="col">Área Junín <br>MANZANELLI, Dario Alberto</div></div></li>



</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 18/10/2024 11:53</p>