<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=3">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Ministerio de Gobierno<br>ENDEIZA, Facundo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaría Privada<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Asesoría Legal<br>GATICA, Juliana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Asesoría Contable y Presupuestaria<br>UCELAY LOMBARDI, Sandra Haydee</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Subdirección de Comunicación Institucional<br>FAES, Yanina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Subdirección de Asistencia Informática<br>DALVIT SANTANDER, Cintia Lorena</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Despacho<br>SANCHEZ, Liliana Alejandra</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Subdirección Vinculación con la Comunidad<br>BARROSO, Sandra Elizabeth</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 2.</span></div><div class="col">Dirección de Relaciones Laborales<br>SIN DESIGNACIÓN</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 2.1.</span></div><div class="col">Subdirección de Relaciones Laborales - Primera Circunscripción<br>BALMACEDA AMESTOY, Ivana Beatriz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 2.2.</span></div><div class="col">Subdirección de Relaciones Laborales - Segunda Circunscripción<br>GOMEZ FERRER, Carlos Emilio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 2.3.</span></div><div class="col">Subdirección de Relaciones Laborales - Tercera Circunscripción<br>ESCUDERO, Luis Ricardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 2.4.</span></div><div class="col">Subdirección Jurídica<br>LANDABURU, Cesar Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 3.</span></div><div class="col">Dirección de Asuntos Municipales<br>AMONDARAIN, Gonzalo Federico</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 3.1.</span></div><div class="col">Subdirección de Control Administrativo y Contable<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 3.2.</span></div><div class="col">Subdirección de Asistencia Jurídica<br>LABORDA CLAVERIE, Valentín</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 3.3.</span></div><div class="col">Subdirección de Capacitación<br>VIGIL, Damian Elbio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 3.4.</span></div><div class="col">Delegación Municipio de Desaguadero<br>GONZALEZ, Sergio Antonio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 4.</span></div><div class="col">Dirección de Registro de Estado Civil y Capacidad de las Personas<br>VALDEVENITEZ, Guillermo Gaston</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 4.1.</span></div><div class="col">Subdirección de Registro de Estado Civil y Capacidad de las Personas - Villa Mercedes<br>GIECO, Lucas Ariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 4.2.</span></div><div class="col">Área de Registro de Estado Civil y Capacidad de las Personas - Villa de Merlo<br>GIMENEZ, Jose Maximiliano</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 5.</span></div><div class="col">Dirección del Registro de la Propiedad Inmueble<br>HEREDIA, Paula Marcela</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 5.1.</span></div><div class="col">Subdirección del Registro de la Propiedad Inmueble<br>AVELLANEDA MUÑOZ, Marisa Laura</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 5.2.</span></div><div class="col">Subdirección de Asesoramiento Técnico General<br>CURTI, Maria Julia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 6.</span></div><div class="col">Dirección de Cultos<br>BERLO, Walter Gustavo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 6.1.</span></div><div class="col">Subdirección de Cultos - Villa Mercedes<br>BORNAND, Erica Susana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 7.</span></div><div class="col">Dirección de Personas Jurídicas<br>DOMINGUEZ, Maria Lorena</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 7.1.</span></div><div class="col">Subdirección de Personas Jurídicas<br>POGGI, Maria Victoria</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 7.2.</span></div><div class="col">Subdirección de Personas Jurídicas - Villa Mercedes<br>LUNA, Marisa Rosana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 7.3.</span></div><div class="col">Subdirección de Fortalecimiento Institucional<br>ACEVEDO, Loreta Romina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 7.4.</span></div><div class="col">Subdirección del Registro Público de Comercio - San Luis<br>TOHME, Maria De Los Milagros</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 7.5.</span></div><div class="col">Subdirección del Registro Público de Comercio - Villa Mercedes<br>SILVESTRE PUENTE, Maria Paula</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 8.</span></div><div class="col">Dirección de Defensa del Consumidor y Lealtad Comercial<br>HISSA, Maria Cecilia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 8.1.</span></div><div class="col">Subdirección de Defensa del Consumidor y Lealtad Comercial<br>NIEVAS BUSTOS, Julieta Maria Victoria</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 8.2.</span></div><div class="col">Subdirección de Defensa del Consumidor y Lealtad Comercial- Villa Mercedes<br>RIBEIRO, Sabrina Griselda</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 9.</span></div><div class="col">Dirección de Derechos y Garantías Constitucionales<br>JUAREZ, Alberto Marcelo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 9.1.</span></div><div class="col">Subdirección de Derechos Humanos<br>AGUIRRE, Mario Javier</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 9.2.</span></div><div class="col">Subdirección del Registro de Deudores Alimentarios y Morosos<br>VASQUEZ, Elio Ramon</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 9.3.</span></div><div class="col">Área de Asistencia a las Víctimas del Delito<br>GOMEZ, Gabriela Roxana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 9.4.</span></div><div class="col">Área de Reinserción Social<br>SAEZ, Jorge Rafael</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 9.5.</span></div><div class="col">Área de Procuraduría Penitenciaria<br>CIMINARI, Maria Eugenia</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 14/11/2024 11:39</p>