<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=2">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Ministerio de Hacienda e Infraestructura Pública<br>ORDÓÑEZ, Néstor Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaría Privada<br>GAIDO RISO, Julieta</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Despacho<br>OROS, Ana Maria</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Asesoría Legal<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Asesoría Contable y Presupuestaria<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Dirección de Comunicación Institucional<br>CALDERÓN, Carlos Darío</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Dirección Jurídica del Ministerio de Hacienda e Infraestructura Pública<br>PAGANO, Roberto Eduardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Dirección General de Hacienda Pública<br>CAPPIELLO, Teresa</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.1.</span></div><div class="col">Dirección de Finanzas y Recursos<br>SOSA HERRERA, Maria Eugenia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.1.</span></div><div class="col">Coordinación Fiscal Federal<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.2.</span></div><div class="col">Subdirección Bancos y Control de Recursos<br>ADARO, Alejandra</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.3.</span></div><div class="col">Subdirección Municipios<br>LIENDO, Maria Eugenia Del Lujan</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.4.</span></div><div class="col">Subdirección Gastos Tarifados y Tasas<br>AHUMADA, Nora Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.5.</span></div><div class="col">Subdirección de Estrategias Financieras<br>PEREZ, Alejandro Javier</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.1.5.1.</span></div><div class="col">Área Mercado de Capitales y Nuevas Herramientas Financieras<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.1.5.2.</span></div><div class="col">Área Monedas Digitales<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.2.</span></div><div class="col">Dirección Provincial de Ingresos Públicos<br>CRESPO, Alberto Raul</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.1.</span></div><div class="col">Subdirección Interna<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.2.1.1.</span></div><div class="col">Área Delegación Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.2.</span></div><div class="col">Subdirección de Gestión de Sistemas<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.3.</span></div><div class="col">Dirección Provincial de Catastro y Tierras Fiscales<br>CRIVELLO, Darío</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.3.1.</span></div><div class="col">Subdirección Provincial de Catastro y Tierras Fiscales<br>MARTIN, María Inés</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.3.1.1.</span></div><div class="col">Área Gestión Catastral<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.3.1.2.</span></div><div class="col">Área Sistema de Información Territorial<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.3.1.3.</span></div><div class="col">Área Valuaciones<br>SCIVETTI, María Jose</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.4.</span></div><div class="col">Dirección de Presupuesto Público<br>BIANCOTTI, Mónica Rita</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.4.1.</span></div><div class="col">Subdirección Seguimiento y Modificaciones Presupuestarias<br>L'HUILLIER, Emilio Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.4.2.</span></div><div class="col">Subdirección Programación Financiera<br>SUAREZ, Jorge Miguel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.5.</span></div><div class="col">Dirección de Compras y Contrataciones<br>LUBERRIAGA, Maria Cecilia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.5.1.</span></div><div class="col">Subdirección de Licitaciones, Eventos y Contrataciones Especiales<br>CASAS DOMINGUEZ, Lucas Jesus</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.5.2.</span></div><div class="col">Subdirección de Concursos y Contrataciones Directas<br>IGLESIAS, Antonio Victor</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.5.3.</span></div><div class="col">Área Registro de Proveedores y Precio Testigo<br>OROZCO MOYANO, Karin Tatiana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.5.4.</span></div><div class="col">Área Informática y Control del Gasto<br>MOLINAR MIN, Karina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.5.5.</span></div><div class="col">Área Legal y Técnica<br>RODRÍGUEZ, Jorge</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.6.</span></div><div class="col">Dirección de Recursos Humanos<br>SIBERT, Francisco Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.6.1.</span></div><div class="col">Subdirección de Análisis y Liquidación de Haberes<br>NAVARRO, Maria Alicia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.6.1.1.</span></div><div class="col">Área Análisis y Liquidación de Haberes<br><small>SIN DESIGNACIÓN</small></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.6.1.2.</span></div><div class="col">Área Liquidación otros entes y empresas del Estado<br>FERNANDEZ, Lorena Elizabeth</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.6.2.</span></div><div class="col">Subdirección Recursos Humanos Docentes<br>TOBARES, Maria Luz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.6.2.1.</span></div><div class="col">Área Recursos Humanos Docentes<br>GARCIA SOSA, Jorge Gabriel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.6.3.</span></div><div class="col">Subdirección Gestión Previsional y Retiros<br>ABRAHIN, Nazir Yamil</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.6.3.1.</span></div><div class="col">Área Gestión Previsional<br>STEVENIN, Jorge Jose Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.6.4.</span></div><div class="col">Subdirección de Capacitación<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.6.5.</span></div><div class="col">Área Control de Personal<br>GOLINI, Clara Natalia Desire</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.6.6.</span></div><div class="col">Área SEMA<br>GRAÑA, Lorena Andrea</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.7.</span></div><div class="col">Contaduría General de la Provincia<br>PECORARI, Omar Dario</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.7.1.</span></div><div class="col">Subcontaduría General de la Provincia<br>PECORARI, Hernan Gustavo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.7.1.1.</span></div><div class="col">Subdirección Control Legal e Informes<br>VILLEGAS, Esteban Cesar</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.7.1.2.</span></div><div class="col">Subdirección Control de Ejecución Presupuestaria<br>SILAS, Malvina Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.7.1.3.</span></div><div class="col">Área Previsional, Municipios y Aportes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.7.7.1.4.</span></div><div class="col">Área Rendiciones<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.8.</span></div><div class="col">Tesorería General de la Provincia<br>VALENZUELA, Walter Daniel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.8.1.</span></div><div class="col">Subdirección de Análisis y Proyecciones<br>PELLEGRINI, Carolina Del Valle</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.8.2.</span></div><div class="col">Subdirección Programación, Control y Pagos<br>ARITO, Maria Guadalupe</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.9.</span></div><div class="col">Dirección de la Caja Social y Financiera de la Provincia de San Luis<br>MAZZINA, Héctor </div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.9.1.</span></div><div class="col">Subdirección Juegos de Azar y de Proyectos Inmobiliarios<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.9.2.</span></div><div class="col">Subdirección Administrativa Contable<br>DI GENNARO, Maria Veronica</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.9.2.</span></div><div class="col">Subdirección Promoción del Ahorro y Seguros<br>THUER, Jeremías José</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.10.</span></div><div class="col">Dirección de Informática<br>HUED, Claudio Daniel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.10.1.</span></div><div class="col">Subdirección Desarrollo y Mantenimiento de Aplicativos<br>GIMENEZ, Claudio Antonio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.10.2.</span></div><div class="col">Subdirección Infraestructura Informática<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.11.</span></div><div class="col">Comisión Reguladora de Energía Eléctrica<br>GIUMELLI, Laura Gisela</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.11.1.</span></div><div class="col">Subdirección Legal<br>FERRARA, Laura Beatriz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.11.2.</span></div><div class="col">Área Técnica de Control de Contrato de Concesión<br>DELFINO, Oscar Santo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.11.3.</span></div><div class="col">Área Contable de Control Tarifario<br>VARELA, Jorge Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.8.</span></div><div class="col">Director General de Infraestructura Pública<br>OFRIA, Fernando Ariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.1.</span></div><div class="col">Subdirección de Control de Certificados y Sistematización de la Obra Pública<br>OSUNA, Victor Mario</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.2.</span></div><div class="col">Dirección Provincial de Vialidad<br>LA MALFA, Jose Angel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.2.1.</span></div><div class="col">Subdirección de Proyectos y Tecnologías<br>ALDONZA, Juan Cruz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.2.2.</span></div><div class="col">Subdirección de Operaciones Estratégicas y de Conservación<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.8.2.2.1.</span></div><div class="col">Área Centro<br>GARCIA, Emilio Francisco Jesus</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.8.2.2.2.</span></div><div class="col">Área Norte<br>BIASSI, Eloy Ramon Ricardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.8.2.2.3.</span></div><div class="col">Área Sur<br>MUÑOZ, Aldo Oscar</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.2.3.</span></div><div class="col">Subdirección de Contrataciones y Control de Gestión<br>ALITTA, Martin Ricardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.3.</span></div><div class="col">Dirección del Ente Control de Rutas<br>PAEZ QUIROGA, Ariel Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.3.1.</span></div><div class="col">Subdirección Mantenimiento de Rutas y Señalización Vial<br>SISSO, Marcelo Eduardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.3.2.</span></div><div class="col">Subdirección Administrativo Contable<br>DIAZ GARRO, Mariela Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.3.3.</span></div><div class="col">Subdirección de Sistemas<br>TULA, Andres Eugenio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.3.4.</span></div><div class="col">Subdirección de Forestación<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.3.5.</span></div><div class="col">Subdirección de Mantenimiento y Balanzas<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.8.3.5.1.</span></div><div class="col">Área Centro<br>ALCARAZ, Mario Ignacio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.8.3.5.2.</span></div><div class="col">Área Norte<br>DATO, Juan Carlos</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.8.3.5.3.</span></div><div class="col">Área Sur<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.4.</span></div><div class="col">Dirección de Obras de Arquitectura y Viviendas<br>ORTIZ, Gladys Marina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.4.1.</span></div><div class="col">Subdirección de Obras de Educación, Salud y Viviendas<br>PECHINI, Maria Pia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.4.2.</span></div><div class="col">Subdirección de Obras de Arquitectura<br>PAGANO, Claudia Graciela</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.4.3.</span></div><div class="col">Subdirección de Precios<br>DAGLIO, Nancy Beatriz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.5.</span></div><div class="col">Dirección de Infraestructura Hídrica y Energética<br>COMASTRI, Corrado Astorre</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.5.1.</span></div><div class="col">Subdirección de Infraestructura Energética<br>MOLINA, Maria Celia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.5.2.</span></div><div class="col">Subdirección de Grandes Obras Hídricas<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo3 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.5.3.</span></div><div class="col">Subdirección de Obras de Agua y Saneamiento<br>MIDLELL, Angel Ali</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 11/09/2024 13:18</p>