<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=11">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Secretaría de Estado Legal y Técnica<br>ZARATE, Fabiana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Privada y Contable<br>NOSTRAY, Matias Nicolas</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Dirección de Control Legal <br>FARIAS, Gustavo Ariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.1</span></div><div class="col">Subdirección Control Legal<br>SIN DESIGNACIÓN</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.2.1.1</span></div><div class="col">Área Control Legal y Técnico 1<br>ROMERO, Maria Pilar</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.2.1.2</span></div><div class="col">Área Control Legal y Técnico 2<br>GATICA SCHMITZ, Micaela Marlene</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.2.1.3</span></div><div class="col">Área Control Legal y Técnico 3<br>SOLARI, Maria Milagros</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.2.1.4</span></div><div class="col">Área Control Legal y Técnico 4<br>WANZO, Marina Vanesa</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.2.1.5</span></div><div class="col">Área Control Legal y Técnico 5<br>FUNES, Miriam Daniela</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.2.1.6</span></div><div class="col">Área Control Legal y Técnico 6<br>PARNISARI, Elsa Judith</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.2.1.7</span></div><div class="col">Área Control Legal y Técnico 7<br>MUÑOZ, Maria Elena</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.2.1.8</span></div><div class="col">Área Control Legal y Técnico 8<br>VOLKER, Virginia Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3</span></div><div class="col">Dirección Vinculación Institucional y Proyectos Estrategicos<br>ALUME SBODIO, Karim Augusto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.1</span></div><div class="col">Oficina Registro de Decretos<br>OJEDA, Oscar</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4</span></div><div class="col">Dirección Boletín Oficial y Judicial<br>FARIAS, Gustavo Ariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.4.1</span></div><div class="col">Área Edición Boletín<br>SIN DESIGNACIÓN</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5</span></div><div class="col">Dirección de Tecnologias de la Información y las Comunicaciones<br>SIN DESIGNACIÓN</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 25/10/2024 09:31</p>