<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=12">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Secretaria de Estado de Actividades Logísticas<br>VOGT, Walter</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaria Privada<br>MÓDICA, Carol Ileana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Despacho<br>MIRANDA, Claudia Betina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Asesoría Legal<br>GROSSO, Mariela Del Valle</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Asesoría Contable y Presupuestaria<br>VERGES ESTEVES, Bernardita María</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Subdirección Comunicación Institucional<br>OCHOA, Facundo Nicolás</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Subdirección de Transporte Multimodal<br>AYELLO, María Guillermina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.1.</span></div><div class="col">Área Logística<br>ESCUDERO, Ángel Daniel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Subdirección de Servicios Logísticos<br>LUGONES , Andrés Eduardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.1.</span></div><div class="col">Área Almacenes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.2.</span></div><div class="col">Área Registro<br>QUIÑONEZ, Ramon Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.8.</span></div><div class="col">Dirección de Agrozal<br>PANSA, Sergio Horacio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.1.</span></div><div class="col">Subdirección de Logística Agropecuaria<br>AGUILERA, Carlos Santiago</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.1.1.</span></div><div class="col">Área Coordinación<br>SIN DESIGNACIÓN</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.9.</span></div><div class="col">Dirección de Comercio Exterior<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.1.</span></div><div class="col">Subdirección de Nuevos Mercados<br>OLAGARAY ALMADA, Maria Guillermina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.1.1.</span></div><div class="col">Área Desarrollo<br>RENOU, Ángel Agustín</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.1.2.</span></div><div class="col">Área Legal<br>CASTILLO CAMARGO, Florencia Yael</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.1.3.</span></div><div class="col">Área Logística<br>DI GENNARO, Ivana Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.10.</span></div><div class="col">Dirección de Zona Franca de Justo Daract<br>ZAMORA, Pablo Eduardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.1.</span></div><div class="col">Subdirección de Zona Primaria Aduanera<br>PALACIOS, Juan Carlos</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.10.1.1.</span></div><div class="col">Área Operaciones<br>PALACIOS, Gisela Carolina</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 18/10/2024 09:58</p>