<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=4">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Ministerio de Salud<br>NIGRA, Lucia Teresa</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaría Privada<br>MICHEL, Miriam Elena</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Despacho<br>QUIROGA, Leonor Angélica</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Área Comunicación Institucional<br>MAURO CELORRIO, María Inés</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Asesoría Legal<br>NOSTRAY, Matias Nicolás</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Dirección de Obra Social del Estado Provincial (D.O.S.E.P.)<br>VERGARA, JORGE ARTURO</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.1.</span></div><div class="col">Subdirección Legal, Despacho y Personal<br>ZALLOCCO, Pablo Sebastián</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.2.</span></div><div class="col">Subdirección de Administración y Finanzas<br>OJEDA FATTORI, Cristian Luciano</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.5.2.1.</span></div><div class="col">Área Tesorería<br>ORTIZ, Julieta Dolores</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.5.2.2.</span></div><div class="col">Área Compras<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.5.2.3.</span></div><div class="col">Área Liquidaciones<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.3.</span></div><div class="col">Subdirección de Servicios y Atención al Afiliado<br>BARRIO, Elena Beatriz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.5.3.1.</span></div><div class="col">Área Farmacias y Planes Especiales<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.5.3.2.</span></div><div class="col">Área Servicios Fuera de la Provincia<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.5.3.3.</span></div><div class="col">Área Afiliaciones y Prestadores<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.5.3.4.</span></div><div class="col">Área Delegaciones del Interior<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.4.</span></div><div class="col">Subdirección D.O.S.E.P. Digital<br>LEDESMA, Jorge Antonio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.5.</span></div><div class="col">Subdirección D.O.S.E.P. Villa Mercedes<br>SORIA, Lucrecia Ines</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.5.5.1.</span></div><div class="col">Área Auditoría<br>BECERRA, Analia Rosana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Dirección General de Gestión de la Salud<br>MATTAR DOMINGUEZ, Maria Arminda</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.1.</span></div><div class="col">Hospital Juan Domingo Perón Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.1.1.</span></div><div class="col">Dirección Médica<br>ARENAS, Berta Hortensia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.1.2.</span></div><div class="col">Dirección Administrativa<br>DE ROSE, Viviana Graciela</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.1.3.</span></div><div class="col">Área RRHH<br>ARENAS, Angela Rocio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.2.</span></div><div class="col">Hospital Pediátrico San Luis<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.1.</span></div><div class="col">Dirección Médica<br>TOLOZA ACHILLES, Rodolfo José</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.2.</span></div><div class="col">Dirección Administrativa<br>ARROYO, Mercedes Mabel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.2.3.</span></div><div class="col">Área RRHH<br>VELAZQUEZ, Silvia Claudia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.3.</span></div><div class="col">Dirección Maternidad Dra. Teresita Baigorria<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.3.1.</span></div><div class="col">Subdirección Auditoría Médica<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.3.2.</span></div><div class="col">Subdirección Auditoría Administrativa<br>FANER PORCHETTO, Barbara Del Valle</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.3.3.</span></div><div class="col">Área RRHH<br>RUSSO, Florencia Natalia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.4.</span></div><div class="col">Maternidad Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.4.1.</span></div><div class="col">Dirección Médica<br>BREZIGAR, Ariel Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.4.2.</span></div><div class="col">Dirección Administrativa<br>MIRANDA, Maria Laura</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.4.3.</span></div><div class="col">Área RRHH<br>MOYANO, Leticia Carolina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.5.</span></div><div class="col">Dirección Centro de Referencia de Rehabilitación (CERPRE)<br>GANDARA, Diego Enrique</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.5.1.</span></div><div class="col">Subdirección Centro de Referencia de Rehabilitación (CERPRE)<br>HEREDIA, Juan Dante</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.6.</span></div><div class="col">Dirección Sistema de Emergencias Médicas Provincial (S.E.M.PRO.)<br>GUZMAN, Mariana Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.6.1.</span></div><div class="col">Subdirección S.E.M.PRO. Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.6.2.</span></div><div class="col">Subdirección S.E.M.PRO. Villa de Merlo<br>RAMIS, Julio Cesar</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.7.</span></div><div class="col">Centro Oncológico Integral<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.7.1.</span></div><div class="col">Dirección Médica<br>ROMERO GUIÑAZU, Diego Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.7.2.</span></div><div class="col">Dirección Administrativa<br>ALEGRIA, Erica Elizabeth</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.8.</span></div><div class="col">Hospital Salud Mental<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.8.1.</span></div><div class="col">Dirección Médica<br>PFISTER, Oliver Magdalena</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.8.2.</span></div><div class="col">Dirección Administrativa<br>FERNANDEZ, Alejandro Daniel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.8.3.</span></div><div class="col">Área RRHH<br>VILLEGAS TOBARES, Anabel Natalia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.9.</span></div><div class="col">Subdirección Prevención y Asistencia en Adicciones<br>PANTANO, Dario Mario</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.10.</span></div><div class="col">Dirección Atención Primaria de la Salud San Luis<br>OVIEDO, Héctor Martin</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.10.1.</span></div><div class="col">Subdirección de Enfermería<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.10.2.</span></div><div class="col">Subdirección Contable<br>AGUERO, María Belén</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.10.3.</span></div><div class="col">Área RRHH<br>ARDUINO, María Sandra</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.11.</span></div><div class="col">Dirección Atención Primaria de la Salud Departamento General Pedernera<br>YNMENSON, Manuel Guillermo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.11.1.</span></div><div class="col">Subdirección de Enfermería<br>SAIRES, Miguel Angel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.11.2.</span></div><div class="col">Área RRHH<br>PÉREZ, Verónica Cecilia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.12.</span></div><div class="col">Dirección Medicina del Interior<br>ESNAOLA, Stella Maris Gabriela</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.12.1.</span></div><div class="col">Subdirección Médica<br>RIQUELME, Raúl José</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.12.2.</span></div><div class="col">Subdirección Enfermería<br>OJEDA, Estela Alejandra</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.12.3.</span></div><div class="col">Subdirección Zonas Sanitarias<br>DEL CASTILLO LUCERO, Valentina Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.12.4.</span></div><div class="col">Área Auditoria de Insumos<br>OLMEDO, Jose Ricardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.12.5.</span></div><div class="col">Área Logística y Movilidad<br>ROSALES, Jose Gabriel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.12.6.</span></div><div class="col">Área Coordinación Agentes Sanitarios<br>HEREDIA, Carmen Susana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.12.7.</span></div><div class="col">Área Capacitación y RRHH<br>ALTAMIRANO OJEDA , Patricia Gestsemany </div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.12.8.</span></div><div class="col">Área Compras<br>FUNES, Walter Manuel Timoteo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.13.</span></div><div class="col">Subdirección Sistema de Información Sanitaria y Tecnología<br>L'HUILLER, Cesar Guillermo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.14.</span></div><div class="col">Subdirección Vinculación Centros Privados de Salud<br>ALVAREZ, Jorge Luis</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.15.</span></div><div class="col">Dirección Epidemiologia y Bioestadística<br>RIBBA, Edgar Antonio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.15.1.</span></div><div class="col">Subdirección Enfermedades Transmisibles<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.15.2.</span></div><div class="col">Subdirección Enfermedades No Transmisibles<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.15.3.</span></div><div class="col">Subdirección Laboratorio Salud Pública<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.6.15.3.1.</span></div><div class="col">Área Bioquímica<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel5"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»»» 1.6.15.3.2.</span></div><div class="col">Área Biología Molecular<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.16.</span></div><div class="col">Dirección Fármacos e Insumos Médicos<br>RODRÍGUEZ, Stella Maris</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.16.1.</span></div><div class="col">Subdirección Logística<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.16.2.</span></div><div class="col">Área Suministro y Control de Stock<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.17.</span></div><div class="col">Dirección Maternidad e Infancia<br>LUNA, Analía Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.18.</span></div><div class="col">Programa SUMAR<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.19.</span></div><div class="col">Dirección Salud Sexual Reproductiva y No Reproductiva<br>MOYANO, Jose Gabriel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.20.</span></div><div class="col">Dirección Prevención y Promoción de la Salud<br>DE LA VEGA, Sandra del Valle</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.6.20.1.</span></div><div class="col">Área Adultos Mayores<br>RIQUELME, Raul Jose</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Dirección General de Gestión Administrativa y RRHH<br>FERNANDEZ, Ivana Elisabeth</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.1.</span></div><div class="col">Dirección Autogestión Hospitalaria<br>FABREGA CERDA, Ricardo Andrés</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.1.</span></div><div class="col">Área Facturación<br>NOGUEROL, Martin</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.1.2.</span></div><div class="col">Área Cobranzas<br>OLARIAGA GIMÉNEZ, María Celeste</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.2.</span></div><div class="col">Programa Centro Único de Coordinación de Ablación e Implantes (C.U.C.A.I.)<br>OCHOA, Jorge Marcelo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.3.</span></div><div class="col">Dirección Recursos Humanos<br>AOSTRI, Jorge Luis</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.3.1.</span></div><div class="col">Subdirección Capacitación y Residencias<br>WEIHER, Marcela Patricia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.3.2.</span></div><div class="col">Área Asuntos Profesionales<br>ORTIZ PONCE, Nora Myriam </div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.4.</span></div><div class="col">Dirección de Infraestructura Hospitalaria y Centros de Salud<br>VRBOS, Daniel Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.4.1.</span></div><div class="col">Subdirección Control de Obras<br>TOLEDO, Edgar Humberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.4.2.</span></div><div class="col">Subdirección Equipamiento y Bioingeniería<br>RAMBAUDI, Luciano Rene</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.5.</span></div><div class="col">Subdirección Auditoría Sanitaria<br>LUCERO ESTRADA, Maria Belen</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.6.</span></div><div class="col">Subdirección Servicios Tercerizados<br>ARCE, Laura Viviana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.7.</span></div><div class="col">Subdirección Incluir Salud<br>BARROSO FERREYRA, Maria Lilia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.8.</span></div><div class="col">Subdirección Movilidad<br>CARUSO, Gustavo Ariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.9.</span></div><div class="col">Subdirección Emergencia Sanitaria<br>DELGADO, Silvia Marcela</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 24/10/2024 11:26</p>