<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=1">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Secretaría General de la Gobernación<br>CARBONELL, Romina Andrea</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaría Privada<br>PARIS, María Verónica</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Asesoría Legal<br>GIBOIN, Maria Paula</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Asesoría Contable y Presupuestaria<br>COSENTINO, Fatima Beatriz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Despacho<br>PANNOCCHIA, Marisa Isabel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.4.1.</span></div><div class="col">Área Mesa General de Entradas, Salidas y Archivo<br>LOZA ALIAGA, Ana María </div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Secretaria Privada de la Gobernación<br>MOLINA, Maria Elida del Carmen</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Secretaría Privada de la Vice Gobernación<br>ENDEIZA, Diego Luis</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Dirección de Intendencia La Pedrera<br>SOSA, Maria Fernanda</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.8.</span></div><div class="col">Dirección de Intendencia de Edificios Públicos<br>DEL CASTILLO GUERRA, Mauricio Denny</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.1.</span></div><div class="col">Área Centro Administrativo “Ex Casa de Gobierno”<br>FLORES MORALES, Matias Emmanuel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.9.</span></div><div class="col">Dirección de Intendencia Molino Fénix<br>GONZALEZ, Pablo Fernando</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.10.</span></div><div class="col">Escribanía General de Gobierno<br>LABORDA, Juan José</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.1.</span></div><div class="col">Subdirección de Escribanía General de Gobierno<br>GIANFELICI, Mirna Sofia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.11.</span></div><div class="col">Dirección de Actividades Oficiales<br>ESCALANTE, Roxana Elisabeth</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.1.</span></div><div class="col">Subdirección Protocolo<br>OROZCO, Monica Beatriz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.12.</span></div><div class="col">Dirección Jóvenes Becarios<br>RINAUDO, Jessica</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.12.1</span></div><div class="col">Subdirección Jóvenes Becarios<br>CORREA, Rosa Natalia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.12.1.1</span></div><div class="col">Área Formación y Capacitación<br>ROCA, Luciano</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 24/10/2024 13:15</p>