<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=8">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Ministerio de Seguridad<br>SOSA, Nancy Veronica</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaría Privada<br>DIEZ, Simon Joel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Despacho<br>VELAZQUEZ, Jesus Juan Pablo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Asesoría Legal<br>MUÑIZ OLIVERA AGUIRRE, María Adelaida</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.3.1.</span></div><div class="col">Subdirección Recursos Humanos<br>BARROSO, Carlos Remigio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.3.1.1.</span></div><div class="col">Área de Gestión de Retiros Policía de la Provincia y Personal Penitenciario<br>GAITAN, Natalia Vanina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.3.1.2.</span></div><div class="col">Área de Recursos Humanos<br>HERRERA, Cristian Alfredo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.3.2.</span></div><div class="col">Subdirección Tecnología y Seguridad<br>AGÜERO, Walter Fabian</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.3.2.1.</span></div><div class="col">Área Desarrollo y Mantenimiento de Tecnología<br>CAMARGO, Ivana Emilce</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.3.3.</span></div><div class="col">Subdirección Comunicación Institucional<br>JUAREZ, Pablo Ariel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Asesoría Contable y Presupuestaria<br>BARROSO ALCARAZ, Roxana Romina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Dirección Relaciones Institucionales<br>BERRUEZO, Rafael</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.1.</span></div><div class="col">Área Reglamentaciones<br>VERA, Emiliano Daniel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.5.2.</span></div><div class="col">Área Legal<br>COPPOLA, Nicolás Damián</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Policía de la Provincia de San Luis - Jefatura de Policía<br>VIEYTES, Pablo Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.1.</span></div><div class="col">Sub-Jefatura de Policía<br>TELLO, Alberto Nicolas</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.2.</span></div><div class="col">Área Legal<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.3.</span></div><div class="col">Área Contable<br>LUQUEZ, Dario Esteban</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.4.</span></div><div class="col">Área Presupuestaria<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Dirección Prevención Ciudadana<br>SOLER, Diego Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.1.</span></div><div class="col">Subdirección de Tecnología Comunitaria<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.2.</span></div><div class="col">Subdirección de Coordinación Operativa y Logística<br>RAMOS, Luis Angel Osvaldo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.1.</span></div><div class="col">Área Coordinación Juan Martín de Pueyrredón (Urbana)<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.2.</span></div><div class="col">Área Coordinación Juan Martín de Pueyrredón (Interior)<br>QUIROGA CUENCA, Daniela Noemi</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.3.</span></div><div class="col">Área Coordinación General Pedernera (Urbana)<br>BOGADO, Patricia Adriana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.4.</span></div><div class="col">Área Coordinación General Pedernera (Interior)<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.5.</span></div><div class="col">Área Coordinación Junín<br>LIONE, Vanesa Beatriz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.6.</span></div><div class="col">Área Coordinación Ayacucho<br>LLANOS, Teresita Mabel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.7.</span></div><div class="col">Área Coordinación Chacabuco<br>BALARI, Ezio Franco</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.8.</span></div><div class="col">Área Coordinación Gobernador Dupuy<br>ESTRADA, Maria Del Carmen</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.9.</span></div><div class="col">Área Coordinación Libertador General San Martín<br>CHAVEZ, Edgar Bautista</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.10.</span></div><div class="col">Área Coordinación Coronel Pringles<br>ROJAS, Michael Nicolas</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.2.11.</span></div><div class="col">Área Coordinación Belgrano<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.3.</span></div><div class="col">Subdirección Gestión Administrativa<br>MARINELLI, Lucas Nicolas</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.3.1.</span></div><div class="col">Área Recursos Humanos<br>GATICA, Fatima Johana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.7.3.2.</span></div><div class="col">Área Contable<br>ROJAS, Alvarez Gabriela</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.8.</span></div><div class="col">Dirección Seguridad Vial<br>CARBONELL, Paola Romina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.1.</span></div><div class="col">Área Contable<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.2.</span></div><div class="col">Subdirección Coordinación Operativa<br>GARAY, Diego Roberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.2.1.</span></div><div class="col">Área Observatorio y Prevención Vial<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.2.2.</span></div><div class="col">Área Estrategia, Coordinación y Planificación<br>BOULIN, Jorge Roberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.2.3.</span></div><div class="col">Área Recursos Humanos y Logística<br>DANTUR SPAGNUOLO, Micaela Mariana</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.8.2.4.</span></div><div class="col">Área Capacitación y Extensión Educativa<br>GALDAME, Liliana Andrea</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.3.</span></div><div class="col">Subdirección Unidad Provincial de Juzgamiento de Contravenciones de Tránsito<br>LARA FERRERO, Alejandro Josue</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.4.</span></div><div class="col">Subdirección Innovación Tecnológica en Seguridad Vial<br>CARBONELL, Matias Esteban</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.9.</span></div><div class="col">Instituto Superior de Seguridad Pública de la Provincia - Rectorado<br>VELAZQUEZ, Gerardo Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.1.</span></div><div class="col">Vicerrectorado<br>DELGADO, Paula Antonia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.2.</span></div><div class="col">Subdirección Académica<br>OJEDA, Maria Beatriz</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.2.1.</span></div><div class="col">Escuela de Cadetes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.2.2.</span></div><div class="col">Escuela de Sub Oficiales y Agentes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.3.</span></div><div class="col">Subdirección Capacitación y Profesionalización Continua<br>MARTINEZ, Maria Soledad</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.3.1.</span></div><div class="col">Escuela Superior<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.4.</span></div><div class="col">Subdirección Gabinete Interdisciplinario<br>CORREA, Blanca Rosa</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.5.</span></div><div class="col">Subdirección Administrativa<br>RODRIGUEZ, Sonia Esther</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.5.1.</span></div><div class="col">Área Legal<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.5.2.</span></div><div class="col">Área Recursos Humanos<br>MANSO, Matias Nicolas</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.5.3.</span></div><div class="col">Área Informática<br>BERG, Nicolas Emanuel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.9.5.4.</span></div><div class="col">Área Contable<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.10.</span></div><div class="col">Dirección Prevención y Gestión de Emergencias<br>LÓPEZ , Marcos Sebastián</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.1.</span></div><div class="col">Subdirección Coordinación General Operativa<br>PEREZ, Gonzalo Alberto</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.10.1.1.</span></div><div class="col">Área de Recursos Humanos y Logística<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.10.1.2.</span></div><div class="col">Área de Capacitación y Protocolos<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.2.</span></div><div class="col">Subdirección Operativa Norte<br>GONZALEZ, Angel Matias</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.3.</span></div><div class="col">Subdirección Operativa Sur<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.10.4.</span></div><div class="col">Área Administrativa<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.10.4.1.</span></div><div class="col">Área Contable<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.11.</span></div><div class="col">Dirección General del Servicio Penitenciario Provincial<br>MANTELLI, Karina</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.1.</span></div><div class="col">Subdirección General del Servicio Penitenciario Provincial<br>SERRANO, Juan Carlos</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.2.</span></div><div class="col">Área Legal y Administrativa<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.3.</span></div><div class="col">Subdirección Revinculación<br>SOSA, Mariangeles</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.3.1.</span></div><div class="col">Área Contable<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.3.2.</span></div><div class="col">Área Administrativa<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.4.</span></div><div class="col">Subdirección Técnica-Profesional<br>MOZO, Cesar Horacio</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.4.1.</span></div><div class="col">Área Contable<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.4.2.</span></div><div class="col">Área Talleres<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.11.5.</span></div><div class="col">Subdirección Recursos Humanos<br>ARABEL, Veronica Cecilia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel4"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»»» 1.11.5.1.</span></div><div class="col">Área Gestión Contable<br>PISCHETZ, Pablo Daniel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.12.</span></div><div class="col">Dirección Infraestructura en Seguridad<br>VEGA, Leila</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.12.1.</span></div><div class="col">Área Contable<br>LUCERO JOFRE, Franco Hector</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.12.2.</span></div><div class="col">Área Relevamiento y Mantenimiento<br>MUÑIZ OLIVERA AGUIRRE, Liliana Maria</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.13.</span></div><div class="col">Dirección Tecnológica en Seguridad<br>SALOMÓN, Alejandro Javier</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.1.</span></div><div class="col">Subdirección Centro Monitoreo San Luis<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.2.</span></div><div class="col">Subdirección Centro Monitoreo Villa Mercedes<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.13.3.</span></div><div class="col">Subdirección Centro Monitoreo Villa de Merlo<br><small>SIN DESIGNACIÓN</small></div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 11/09/2024 13:18</p>