<p class="fs-5 py-2">Esta sección se encuentra en constante proceso de actualización. Si encuentra algún error o tiene algún comentario, <a href="../../consulta/?org=19">contáctenos</a>.</p>
<ul class="list-group mt-3 mb-5">
<li class="list-group-item fs-5 py-3 grupo1 nivel1"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">1.</span></div><div class="col">Secretaría de Estado de Transporte<br>CIANCHINO CHIOFALO, Victor Andres</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.1.</span></div><div class="col">Secretaría Privada<br>GIUNTA CHIOFALO, Maria Cecilia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.2.</span></div><div class="col">Asesoría Contable y Presupuestaria<br>PARNISARI PASCUARELLI, Juan Pablo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.3.</span></div><div class="col">Subdirección de Comunicación Institucional<br>AVILA, Evelina Elizabeth</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.4.</span></div><div class="col">Despacho<br>FLORES MORALES, Alejandra Eugenia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo1 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.5.</span></div><div class="col">Asesoría Legal<br>LEYES, Rocio Ayelen</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.6.</span></div><div class="col">Dirección de Transporte<br>BUSTO GONZALEZ, Jonathan Gabriel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.1.</span></div><div class="col">Subdirección de Gestión, Supervisión y Control del Sistema de Transporte<br>AMIEVA OLIVARES, Federico Augus</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.2.</span></div><div class="col">Subdirección de Gestión, Supervisión y Control del Sistema de Transporte No Regular<br><small>SIN DESIGNACIÓN</small></div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.3.</span></div><div class="col">Subdirección de Control de Transporte Provincial<br>TORRES, Luis Rubén</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.4.</span></div><div class="col">Área Control de Transporte General Pedernera y Gobernador Dupuy<br>GIRARDI, Ruben Orlando</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.6.5.</span></div><div class="col">Área Control y Supervisión de Transporte Junín y Coronel Pringles<br>ALTAMIRANO, Juan Carlos</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.7.</span></div><div class="col">Dirección de Innovación y Desarrollo Tecnológico de Transporte<br>BRUNA, Damian Augusto Exequiel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.7.1.</span></div><div class="col">Subdirección de Gestión Integral de Transporte<br>MANCHENTO, Marcelo Sebastian</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.8.</span></div><div class="col">Dirección de Terminales e Integración Regional<br>SORIA, Maria Guadalupe</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.1.</span></div><div class="col">Área Administración Terminal de Ómnibus de Villa de Merlo<br>PISANI, Jorge Del Valle</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.2.</span></div><div class="col">Área Administración Terminal de Ómnibus de Buena Esperanza<br>VILLARROEL, Victor Daniel</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.3.</span></div><div class="col">Área Administración Terminal de Ómnibus de Anchorena<br>BAEZ, Patricio Javier</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.4.</span></div><div class="col">Área Administración Terminal de Ómnibus de Luján<br>SANCHEZ, Estela Herminia</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.5.</span></div><div class="col">Área Administración Terminal de Ómnibus de La Toma<br>PIÑEIRO, Gilda Azucena</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.6.</span></div><div class="col">Área Administración Terminal de Ómnibus de Fraga<br>MUÑIZ GHIGLIA, Maria Lujan</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.8.7.</span></div><div class="col">Área Administración Terminal de Ómnibus de Villa de la Quebrada<br>ALCARAZ, Hugo Felipe</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel2"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">» 1.9.</span></div><div class="col">Ente Estación de Interconexión Regional de Ómnibus de San Luis (EDIRO)<br>a/c. CIANCHINO CHIOFALO, Victor Andres</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.1.</span></div><div class="col">Dirección Administrativa<br>ESPOSITO CORDERO, Diego Eduardo</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.2.</span></div><div class="col">Asesoría Contable y Presupuestaria<br>ORTIZ, Tamara Antonella</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.3.</span></div><div class="col">Subdirección de Mantenimiento<br>GIUNTA, Luciano Nicolas</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.4.</span></div><div class="col">Área Recursos Humanos<br>JUAREZ, Daniel Alejandro</div></div></li>
<li class="list-group-item fs-5 py-3 grupo2 nivel3"><div class="row"><div class="col-auto sin-padding-right"><span class="nivel-symbol">»» 1.9.5.</span></div><div class="col">Área Insumos<br>CUELLO, Maria Josefina</div></div></li>
</ul>
<p class="fs-5 py-2">Última actualización del organigrama: 21/10/2024 13:10</p>